In [42]:
M = Matrix(ZZ, [[1,0,0], [0,1,0], [0,0,1]])

In [43]:
print(M)

[1 0 0]
[0 1 0]
[0 0 1]


In [44]:
L=IntegralLattice(M)
print(L)

Lattice of degree 3 and rank 3 over Integer Ring
Standard basis 
Standard scalar product


In [45]:
U = Matrix(ZZ, [[1,23,54], [0,1,84], [0,0,1]])
print(U)
print(U.determinant())

[ 1 23 54]
[ 0  1 84]
[ 0  0  1]
1


In [46]:
B = Matrix(ZZ,M*U)
print(B)
print(span(M)==span(B))
print(B.det())
print(sqrt((B.transpose()*B).det()))

[ 1 23 54]
[ 0  1 84]
[ 0  0  1]
True
1
1


In [47]:
B_=B.gram_schmidt()[0]
print(B_)

[           1           23           54]
[  -4559/3446 -101411/3446   21639/1723]
[1878/3533941  -84/3533941    1/3533941]


In [48]:
B[0]*B_[2]

0

In [49]:
A = Matrix([[2,1],[1,3]])

In [50]:
A.gram_schmidt()[0]

[ 2  1]
[-1  2]

In [51]:
print(B,'\n')
dual=B.inverse()
print(dual,'\n')
dual=dual.transpose()
print(dual,'\n')

[ 1 23 54]
[ 0  1 84]
[ 0  0  1] 

[   1  -23 1878]
[   0    1  -84]
[   0    0    1] 

[   1    0    0]
[ -23    1    0]
[1878  -84    1] 



In [52]:
B*dual.transpose()

[1 0 0]
[0 1 0]
[0 0 1]

In [53]:
A = Matrix([[2,5,3],[4,7,9],[3,7,8]])
lattice = Matrix(GF(11),A)
print(lattice)
print('det = ',lattice.det())

[2 5 3]
[4 7 9]
[3 7 8]
det =  4


In [54]:
u1 = Matrix(GF(11),[[1,23,4],[0,1,87],[0,0,1]])
print(u1)
print('det u1 =',u1.det())
u2 = Matrix(GF(11),[[1,5,4],[0,1,4],[0,0,1]])
print(u2)
print('det u2 =',u2.det())

[ 1  1  4]
[ 0  1 10]
[ 0  0  1]
det u1 = 1
[1 5 4]
[0 1 4]
[0 0 1]
det u2 = 1


In [55]:
basis = lattice*u1
print(basis)
print(basis.det())
basis = lattice*u2
print(basis)
print(basis.det())

[ 2  7  6]
[ 4  0  7]
[ 3 10  2]
4
[2 4 9]
[4 5 9]
[3 0 4]
4


In [56]:
A.LLL()

[-1  0 -1]
[-2  2  2]
[-2 -3  1]

In [57]:
from sage import plot

def subsets(s):
    n_elems = len(s)
    n_subsets = 2**len(s)
    for i in range(0,n_subsets):
        sub = []
        for j in range(0,n_elems):
            if (i >> j & 1):
                sub.append(s[j])
        yield sub

def plot_lattice(L,dim, **options):
    dim = dim
    basis = L.embedded_basis()
    basis = sum(([-v, v] for v in basis), [])
    points = [sum(v, L(0)) for v in subsets(basis)]
    points = [tuple(v.list()) for v in points]
    points = set(points)
    if dim not in (2, 3):
        raise ValueError("only 2-dimensional and 3-dimensional lattices can be plotted")
    return plot.point.points(points)
gram_matrix = lambda M: matrix(ZZ, M.nrows(), M.ncols(), lambda i, j: M[i]*M[j])
LatticeSign = lambda M: Integer(sum(x / abs(x) for x in gram_matrix(M).eigenvalues()))

In [58]:
LatticeSign(A)

3

In [59]:
gram_matrix(M)

[1 0 0]
[0 1 0]
[0 0 1]

In [60]:
B.LLL()

[ 0  0  1]
[ 0  1  0]
[-1  0  0]

In [63]:
dual_lattice = lambda M: M * (M.transpose() * M).inverse()
u1_ = dual_lattice(u1); u1_

[ 1  0  0]
[10  1  0]
[ 6  1  1]

In [64]:
u1*u1_.transpose()

[1 0 0]
[0 1 0]
[0 0 1]